library:
  source-dirs: src
tests:
  compiler-latte-test:
    source-dirs: test
    main: Spec.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - compiler-latte
copyright: 2018 Author name here
maintainer: example@example.com
dependencies:
- pretty
- parsec
- mtl
- base >= 4.7 && < 5
- text
- containers
- bytestring
name: compiler-latte
version: 0.1.0.0
extra-source-files:
- README.md
- ChangeLog.md
author: Author name here
github: githubuser/compiler-latte
license: BSD3
executables:
  compiler-latte-exe:
    source-dirs: app
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - compiler-latte
description: Please see the README on GitHub at <https://github.com/githubuser/compiler-latte#readme>
